# Generated by Django 5.1 on 2024-11-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('race', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('medical_aid_scheme', models.CharField(blank=True, max_length=100)),
                ('medical_aid_number', models.CharField(blank=True, max_length=100)),
                ('previous_surgeries', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('current_prescription', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('emergency_contact', models.CharField(max_length=15)),
                ('picture', models.ImageField(upload_to='patient_pictures/')),
            ],
        ),
    ]
