# Generated by Django 5.1 on 2024-11-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0002_patient_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_added',
        ),
    ]
